### ISSUE TITLE
Content: Migrate - Cara berkomunikasi antar komponen

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [vuejs-id/blog#10]
Old Content: https://github.com/mazipan/medium-stories/blob/master/2017-09-13_Cara-Berkomunikasi-Antar-Component-di-Vue-js-9544d5059c12.html

**Comment by mandaputtra** [comment]
[commit](https://github.com/vuejs-id/blog/commit/5a61bbb8899831162f79191be3ebb268ed690c44)
