### ISSUE TITLE
Content: Migrate - Cara membuat plugin untuk pemula

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [vuejs-id/blog#11]
Old Content: https://github.com/mazipan/medium-stories/blob/master/2017-09-20_Membuat-Vue-js-Plugin-untuk-pemula-3ae9921ade02.html

**Comment by mandaputtra** [comment]
(commit)[https://github.com/vuejs-id/blog/commit/6bcb737dfc1ad23c5be22b9c930d92131c145902]
