### ISSUE TITLE
Content: Migrate - Membuat search highlight

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [vuejs-id/blog#12]
Old Content: https://github.com/mazipan/medium-stories/blob/master/2017-11-07_Membuat-Search-Highlight-dengan-Vue-js-d47684d5999b.html

**Comment by mandaputtra** [comment]
[commit](https://github.com/vuejs-id/blog/commit/5a61bbb8899831162f79191be3ebb268ed690c44)
