### ISSUE TITLE
Bug - Prism style unexpected

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/blog#26]
![20191104_210254](https://user-images.githubusercontent.com/7221389/68126697-ecf84d00-ff46-11e9-9233-2099e51224e2.jpg)

Should not have border for each line, need to fix it!

**Comment by ikrydev** [comment]
@mazipan 
goals nya apakah seperti ini ?

![Screen Shot 2019-11-05 at 12 05 52](https://user-images.githubusercontent.com/40247655/68180011-aba68280-ffc4-11e9-8396-def74c57b6b0.png)
![Screen Shot 2019-11-05 at 12 05 44](https://user-images.githubusercontent.com/40247655/68180017-b06b3680-ffc4-11e9-9af3-2c8fdd9556e4.png)
