### ISSUE TITLE
Proposal Logo Vue.js Indonesia

### ISSUE THREAD

**Issue by ikrydev** [vuejs-id/blog#3]
[ LOGO BARU ]

SIlahkan Teman Teman Lakukan Vote untuk beberapa opsi logo di bawah ini dengan menggunakan React 👍  atau  🚀  atau ❤️ 

Di tunggu sampai 10 November 2019 :)

**Comment by irfan-maulana-tkp** [comment]
Terima kasih mas @ikrydev 🙏

Saya pribadi kok belum begitu sreg ya.
Kalau bisa jangan pakai kebanyakan warna mas.
Biar enak kalau di sablon di kaos juga.
Coba test diaplikasikan ke beberapa media mas.

Bisa coba dieksplorasi lagi gak ya mas.
Mungkin bisa coba kombinasi logo Vue dengan lambang Garuda.

Tapi kita open banget buat new logo memang.
Soalnya sekarang belum ada logonya sih.

Mohon bantuannya ya 🙏

**Comment by ikrydev** [comment]
Baik mas,,
kalau yang ini gimana ? ada tambahan lagi gk ?


![vuejsid_circle](https://user-images.githubusercontent.com/40247655/68065016-c921e500-fd55-11e9-88bc-e7cf95f9830f.png)
![vuejsid_shadow](https://user-images.githubusercontent.com/40247655/68065017-c921e500-fd55-11e9-990a-c16b0113841c.png)
![vuejs-id_baju](https://user-images.githubusercontent.com/40247655/68065050-1bfb9c80-fd56-11e9-87b6-01b5b3b6b46d.png)

**Comment by mandaputtra** [comment]
Much better

**Comment by mazipan** [comment]
Saya suka nih.
Nunggu dari yang lain ya, gak usah buru2.

**Comment by ikrydev** [comment]
di paskan ke pojok yg warna merah aja kah mas enak nya ?

**Comment by mazipan** [comment]
Saya sih ngelihatnya iya

**Comment by ikrydev** [comment]
![konsep_VueJS-01](https://user-images.githubusercontent.com/40247655/68068042-f3d66280-fd82-11e9-8ace-404f3e0bc927.png)

**Comment by ikrydev** [comment]
![konsep_VueJS-02](https://user-images.githubusercontent.com/40247655/68068043-ffc22480-fd82-11e9-8016-b41f3af0c095.png)

**Comment by mandaputtra** [comment]
React saja pakai :+1: di nomor 1 atau 2

**Comment by mazipan** [comment]
Kita tunggu sampai Senin ya buat votenya...

**Comment by adiatma** [comment]
Yang Garuda kereen sih

**Comment by noursirfan** [comment]
garuda keren mas... unsur indonesia kena...😁

**Comment by mazipan** [comment]
Yang Garuda ada dua, silahkan pilih

**Comment by afifalfiano** [comment]
Mencoba nih mas, bisa dikoreksi atau dijadikan referensi
![VueInd](https://user-images.githubusercontent.com/47497276/68071962-a7a31680-fdb2-11e9-946a-199f86daf371.png)

**Comment by GalangAirlangga** [comment]
Sedikit sarannya temen temen, kalau bisa jangan di ganti warna utama logo vuenya biar identitas si vue nya tetep ada

**Comment by afifalfiano** [comment]
Mencoba mas, bisa dikoreksi dan dijadikan referensi
![g1025](https://user-images.githubusercontent.com/47497276/68072107-7fb4b280-fdb4-11e9-9bf9-678b200074cc.png)
![vuejs_circle](https://user-images.githubusercontent.com/47497276/68072109-7fb4b280-fdb4-11e9-9638-ab46b520a6c6.png)

**Comment by ikrydev** [comment]
![konsep_VueJS-03](https://user-images.githubusercontent.com/40247655/68072471-c0aec600-fdb8-11e9-80fe-864958c8f2f9.png)

**Comment by ikrydev** [comment]
![konsep_VueJS-04](https://user-images.githubusercontent.com/40247655/68072477-cefce200-fdb8-11e9-96b6-c041efa1367b.png)

**Comment by ikrydev** [comment]
![konsep_VueJS-05](https://user-images.githubusercontent.com/40247655/68072479-db813a80-fdb8-11e9-8c43-8a266a318da3.png)

**Comment by mazipan** [comment]
Btw, ini semua text Indonesia-nya typo loh mas 😂

**Comment by alfinsuryaS** [comment]
Logonya udah cukup baik, cuman kalo dari saya ada beberapa saran. Sebenernya logo itu kan identitas, selain itu juga ada beberapa makna didalamnya, klo ini kenapa hrus dirubah lagi, ada tambahan burung garuda? Itu si merubah logo/identitas itu sendiri. "A simple logo design allows for easy recognition and allows the logo to be versatile & memorable", vue js sendiri udah mempunyai logo yg sangat baik, seharusnya utk menunjukkan atau menambahkan identitas Indonesia di logo tersebut, cukup dengan warna merah putih saja orang sudah tau kok itu adalah ciri identitas Indonesia. Bisa juga dengan menggunakan teks, tpi tidak merubah bentuk logo tersebut, terimakasih.

**Comment by mandaputtra** [comment]
@alfinsuryaS Menurut saya tidak apa dirubah sedikit, itu juga simple cuma dua warna ditambahin garuda, identitas kalau *ini lho Vuejs Indonesia*.

Jika disamakan -- mengingat banyak juga yang menyematkan beberapa perubahan pada logo tergantung dimana komunitas vuejs itu berada. Seperti Vue London, Dublin, dan sebagainya.

**Comment by alfinsuryaS** [comment]
> @alfinsuryaS Menurut saya tidak apa dirubah sedikit, itu juga simple cuma dua warna ditambahin garuda, identitas kalau _ini lho Vuejs Indonesia_.
> 
> Jika disamakan -- mengingat banyak juga yang menyematkan beberapa perubahan pada logo tergantung dimana komunitas vuejs itu berada. Seperti Vue London, Dublin, dan sebagainya.

It's not recommended ya, "try keeping a core of the logo unchanged and build variations only on certain elements." ini contoh yg pling baik [FedEx](http://i.stack.imgur.com/GGATc.png). Dan ada beberapa yg hrus diperhatikan disini  => "Please do NOT use it to print custom t-shirts." [VueJS Artworks](https://github.com/vuejs/art).

**Comment by kamalhm** [comment]
Agree with @alfinsuryaS, burungnya pun menurut saya masih terlihat generik, merah putih sudah sangat mewakili dan sangat simple, just like Vue's values

**Comment by mazipan** [comment]
I decide to hide some of our comments to make people easier to find the options.

**Comment by mazipan** [comment]
Kita akan menutup vote, dan vote terbanyak ada di [Logo 1](https://github.com/vuejs-id/blog/issues/3#issuecomment-549021668)

![20191110_091706](https://user-images.githubusercontent.com/7221389/68537691-e892c080-039a-11ea-95ea-56f06d029008.jpg)

**Comment by mazipan** [comment]
Mas @ikrydev, Minta bantuan PR assets nya ke Repo [logo-assets](https://github.com/vuejs-id/logo-assets) ya...

Minta beberapa variasi tipe file juga: jpg, png, svg sama raw file nya.
Background juga dibuat dua, yang tanpa background/transparan dan yang pakai background circle black.

Minta assets yang HD dan yang small.

Terima kasih juga buat semua yang sudah ikut menyumbangkan karyanya dan yang sudah ikut bantu vote.
