### ISSUE TITLE
Add GA

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/blog#48]
Tracking ID for blog.vuejs.id is `UA-166364803-1`

**Comment by mazipan** [comment]
Prefer use this plugin:

https://gridsome.org/plugins/@gridsome/plugin-google-analytics

**Comment by mandaputtra** [comment]
Sudah teriplementasi https://github.com/vuejs-id/blog/blob/a3bdcaab33025dcaac84a3ecbe9dc2362590ce22/gridsome.config.js#L44
